### PR TITLE
Allow struct collections

### PR DESCRIPTION
**Pull request by bsagal**
Fix bug #447

### CODE REVIEW

**Comment by zjklee** [comment]
Hello @bsagal 
Can you please add a test that covers the bug?

**Comment by bsagal** [comment]
In order to test all the fixed cases I will need to create struct implementers of the various collection interfaces.

For `IList<T>` I can use the `System.Collections.Immutable.ImmutableArray<T>`, however this will only test one problematic case.
Additionally this will require and extra dependency on `System.Collections.Immutable`.

I am unaware of any struct implementations of all the collection interfaces included in the framwork and am unaware of a way to mock stucts.

As far as I am aware to only solution is to create struct implementations for all the collection interfaces.

Where would you suggest I place in implemations in the source tree?

**Comment by zjklee** [comment]
Having an extra dependency in tests is fine. I think having coverage at least for `ImmutableArray` should be good enough at this point.

**Comment by bsagal** [comment]
Ok understood.

This will help test a stuct `IList<T>`.
What should i do about testing stuct implamentations of the other collection interfaces such as `IDictionary<T>`. They were also fixed.

**Pull request merged**
