### PR TITLE
Update of TFM & dependency optimisation

### PR DESCRIPTION
**Pull request by thompson-tomo**
By adjusting the TFM'S we have been able to produce a package with no dependencies on the latest frameworks hence an optimised dependency graph.

The following frameworks have been added:
- Net 6

The following frameworks even though requested was not added:
- Net 5

The following frameworks were removed:
- Net 4.5.2
- Net 4.6

Closes: #573
Closes: #415

### CODE REVIEW

**Review by oformaniuk — CHANGES_REQUESTED** [review]
Consider dropping `net5` as it is not supported anymore and adding `net8`.

**Comment by thompson-tomo** [comment]
I don't see a benefit in adding dotnet 8 as the dotnet 6 compilation will be used. Will remove net 5.

Thoughts on also dropping net 452, net 46 as it is the same as th3 net 451 compilation.

**Review by oformaniuk — APPROVED** [review]

**Comment by oformaniuk** [comment]
> Thoughts on also dropping net 452, net 46 as it is the same as the net 451 compilation.

Yes, this is a good idea to optimize monikers 👍

**Comment by thompson-tomo** [comment]
@oformaniuk i have just gone & dropped those 2 TFM's from the package.

**Comment by oformaniuk** [comment]
@thompson-tomo , CI pipeline is now broken: https://github.com/Handlebars-Net/Handlebars.Net/actions/runs/8524444266/job/23349047350

**Comment by thompson-tomo** [comment]
@oformaniuk should be Fixed in #576

**Pull request merged**
