### PR TITLE
Add one More Compile Method Overload

### PR DESCRIPTION
**Pull request by HaruTzuki**
I am working in a project and I thought this will be a great method.

### CODE REVIEW

**Comment by rexm** [comment]
I'm curious what is the use case for this?

**Comment by HaruTzuki** [comment]
In order to compile a text with handlerbars you need first to compile the text to take the template and after that you need to pass the object. I decided it will be great this to happens in one line if you need to use it in a lamda expression e.g.

`public string GetText(string source, object handles)=>Handlebars.Compile(source, handles); // something like that.`

**Comment by HaruTzuki** [comment]
Ok then... Delete the PR.

**Comment by rexm** [comment]
Happy to reopen if anyone feels strongly enough about this to address the ergonomics issue.

**Pull request closed without merging**
